name: arif_audio_player
description: "A professional music player app for iOS and Android built with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # iOS Files App / Storage থেকে অডিও ফাইল সিলেক্ট করার জন্য
  file_picker: ^8.0.0

  # হাই-পারফর্ম্যান্স অডিও ইঞ্জিন
  just_audio: ^0.9.36

  # iOS Control Center, Lock Screen ও AirPods কন্ট্রোলের জন্য
  just_audio_background: ^0.0.1-beta.13

  # একাধিক প্লেলিস্ট ও গান লোকালি সেভ রাখার জন্য
  shared_preferences: ^2.2.2

  # ফাইল ডিরেক্টরি সঠিকভাবে অ্যাক্সেস করার জন্য
  path_provider: ^2.1.2

  # আইকন সেটের জন্য
  cupertino_icons: ^1.0.8
  rxdart: ^0.28.0 # 🔥 সিকবার স্মুথ করার জন্য

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
